apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skupper
spec:
  destination:
    namespace: openshift-operators
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops/skupper/rhsi/base
    repoURL: 'https://github.com/pprosser-redhat/quarkus-superheroes-skupper.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true