apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: phils-connector  
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1  
  config:
    snapshot.mode: when_needed
    database.hostname: philsmysql  
    database.port: 3306
    database.user: phil
    database.password: phil
    database.server.id: 18999  
    database.server.name: philsmac  
    database.include.list: phil
    schema.history.internal.kafka.bootstrap.servers: my-cluster-kafka-bootstrap:9092  
    schema.history.internal.kafka.topic: schema-changes.phil
    topic.prefix: philsmac